function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(32)=1.282051282051282;
    params(46)=(1+params(5))*params(10)/params(11);
    params(34)=exp(params(5))/params(11)-(1-params(2));
    params(35)=(1/(1+params(30))*params(1)^params(1)*(1-params(1))^(1-params(1))*1/params(34)^params(1))^(1/(1-params(1)));
    params(36)=params(35)/params(34)*params(1)/(1-params(1));
    params(37)=params(36)^params(1)-params(34)*params(36)-params(35);
    params(39)=params(36)^params(1)-params(37);
    params(40)=params(36)*exp(params(5))*(1-(1-params(2))*exp((-params(5))));
    params(41)=params(39)*1/params(32)-params(40);
    lambdaL=params(41)^(-1)*(exp(params(5))-params(11)*params(6))/(exp(params(5))-params(6));
    params(9)=(params(35)*lambdaL/params(34))^(1/(1+params(12)));
    params(42)=params(36)*params(9);
    params(43)=params(39)*params(9);
    params(44)=params(40)*params(9);
    params(45)=params(41)*params(9);
    params(38)=params(37)*params(9);
    omega=((1-params(1))^(1-params(1))*params(1)^params(1)*1/(1+params(7))*(1/params(34))^params(1))^(1/(1-params(1)));
    params(33)=(1-params(11)*params(13))*(1-params(13))/(params(13)*(1+params(11)*params(3)));
    params(59)=(1-params(11)*params(14))*(1-params(14))/(params(14)*(1+params(11))*(1+params(12)*(1+1/params(8))));
    % Auxiliary equations
end
